### PR TITLE
Tweak the wording of "Tracks" references in the `check_tracks` plugin

### PR DESCRIPTION
**Pull request by mokagio**
See commit messages for the rationale behind the individual changes

### CODE REVIEW

**Review by iangmaia — APPROVED** [review]
Good one 👍 I just followed what was in the Peril rule, but it makes it a lot clearer to refer to the product name using capital letters. Thanks!

**Comment by iangmaia** [comment]
@mokagio FYI, I've updated `add/check-tracks` with the latest changes from `trunk`, so I guess you'll need to rebase this branch onto `add/check-tracks` before merging again.

**Comment by mokagio** [comment]
@iangmaia noted. I might just wait till `add/check-tracks` lands on `trunk`.

**Comment by iangmaia** [comment]
@mokagio worth looking into a rebase now that `add/check-tracks` has landed 🙏

**Comment by mokagio** [comment]
@iangmaia thank for the ping!

**Pull request merged**
